### ISSUE TITLE
Error when testing pipeline library file with named parameters

### ISSUE THREAD

**Issue by bence-takacs** [macg33zr/pipelineUnit#8]
Error when testing pipeline library file that has more than one parameters:

err:
```
groovy.lang.MissingMethodException: No signature of method: addPolicy.call() is applicable for argument types: (tests.library.runAddPolicySpec$__spock_feature_1_0_closure1) values: [tests.library.runAddPolicySpec$__spock_feature_1_0_closure1@17a6c499]
Possible solutions: wait(), any(), wait(long), call(java.lang.String, java.lang.String, java.lang.String, java.lang.String), main([Ljava.lang.String;), each(groovy.lang.Closure)
	at com.lesfurets.jenkins.unit.PipelineTestHelper$_closure4.doCall(PipelineTestHelper.groovy:182)
	at com.lesfurets.jenkins.unit.PipelineTestHelper$_closure3.doCall(PipelineTestHelper.groovy:143)
	at tests.library.runAddPolicySpec.test myshared library code(TestAddPolicy.groovy:25)
```

vars/addPolicy.groovy:
```
def call(String bucketName, String arnToAdd, String profile, String region) {
  ...
}
```

test:
```
class runAddPolicySpec extends PipelineSpockTestBase {

    def "test myshared library code"() {

        given:
        def paramsPassed = {
            bucketName= "..."
            arnToAdd= "..." 
            profile="..."
            region="..."
        }
        callStackPath = 'src'

        when:
        def script = loadScript('vars/addPolicy.groovy')
        script.call(paramsPassed)

        then:
        printCallStack()
        assertJobStatusSuccess()
    }
}
```

...while the given example test with one parameter works: 
exampleJob.jenkins with body `def call(body) {`

Is this a bug or i should do something differently?

**Comment by bence-takacs** [comment]
Still don't work with:
```
def paramsPassed= new Binding('bucketName': "...", arnToAdd: "...", profile:"...", region:"...") 
script.call(paramsPassed)
```

This is the only one that working:
script.call("...", "...", "...", "...")

**Comment by macg33zr** [comment]
Sorry it has taken me a while...day job got in the way. I added another example of a library step with multiple parameters. See 'pipelineLibrary/vars/stepWithParams.groovy' and 'pipelineTests/groovy/tests/library/stepWithParamsTestSpec.groovy'. I think in your first attempt you just need to pass each param in the call() method. Does this help? Please re-open the issue if it doesn't.
